{% set name = "brax" %}
{% set version = "0.14.1" %}
# See https://github.com/conda-forge/brax-feedstock/pull/23#issuecomment-3195617254
# Remove once conda-forge itself sets python_min to 3.10
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/brax/archive/refs/tags/v{{ version }}.zip
  sha256: d8a6760364e3e809318f073cbc06505bc06cb8ae138bf18dbf5e823c3ed07d1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - jaxlib >=0.4.6
    - jax >=0.4.6
    - absl-py
    - dm-env
    - flask
    - flask-cors
    - flax
    - gym
    - numpy
    - ml-collections
    - optax
    - orbax-checkpoint
    - pillow
    - python >={{ python_min }}
    - pytinyrenderer
    - pyyaml >=6.0
    - scipy
    - tensorboardx
    - trimesh
    - typing-extensions
    - grpcio
    - jaxopt
    - jinja2
    - mujoco-python
    - mujoco-mjx
    - etils
    - importlib_resources

test:
  imports:
    - brax
  commands:
    - pip check
    # Running only a few tests as a workaround for https://github.com/conda-forge/brax-feedstock/pull/11#issuecomment-1934257371
    - pytest --pyargs brax -v -k "test_forward2"
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - transforms3d
    - wget
    - git

about:
  home: http://github.com/google/brax
  summary: A differentiable physics engine written in JAX.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - erikfrey
