{% set name = "brax" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/brax/archive/refs/tags/v{{ version }}.zip
  sha256: 3bd37fdb5b9bb694f45c0e75f2c84ab572c04d5682ca5743d353f60a3b0300c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - jaxlib >=0.4.6
    - jax >=0.4.6
    - absl-py
    - dm-env
    - flask
    - flask-cors
    - flax
    - gym
    - numpy
    - ml-collections
    - optax
    - pillow
    - python >={{ python_min }}
    - pytinyrenderer
    - pyyaml >=6.0
    - scipy
    - tensorboardx
    - trimesh
    - typing-extensions
    - grpcio
    - jaxopt
    - jinja2
    - mujoco-python
    - mujoco-mjx
    - etils
    - importlib_resources

test:
  imports:
    - brax
  commands:
    - pip check
    # The testdata cylinder.stl is not shipped with the source archive,
    # so we download it manually
    # See:
    # * https://github.com/google/brax/blob/v0.0.16/brax/tests/physics_test.py
    # * https://github.com/abseil/abseil-py/blob/v1.3.0/absl/testing/absltest.py#L156
    - mkdir -p brax/v1/tests/testdata
    - wget https://github.com/google/brax/raw/v{{ version }}/brax/v1/tests/testdata/cylinder.stl -O brax/v1/tests/testdata/cylinder.stl
    # Skipping a few tests as a workaround for https://github.com/conda-forge/brax-feedstock/pull/11#issuecomment-1934257371
    - pytest --pyargs brax -v -k "test_forward2"
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - transforms3d
    - wget
    - git

about:
  home: http://github.com/google/brax
  summary: A differentiable physics engine written in JAX.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - erikfrey
