{% set name = "brax" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brax-{{ version }}.tar.gz
  sha256: 5cef88b896eccaec819fd2707591f8c99444c49f911781abd6601af161777928

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jaxlib >=0.3.7
    - jax
    - absl-py
    - dataclasses
    - dm-env
    - flax
    - gym
    - numpy
    - optax
    - pillow
    - python >=3.7
    - pytinyrenderer
    - pyyaml >=6.0
    - tensorboardx
    - trimesh
    - typing-extensions
    - grpcio

test:
  imports:
    - brax
  commands:
    - pip check
    - pytest --pyargs brax -v
  requires:
    - pip
    - pytest

about:
  home: http://github.com/google/brax
  summary: A differentiable physics engine written in JAX.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - erikfrey
