{% set name = "brax" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brax-{{ version }}.tar.gz
  sha256: 47ac29511186947b0742de08951a524940de0bdd42b21309fd6a1d067ed32c30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jaxlib >=0.3.7
    - jax
    - absl-py
    - dataclasses
    - dm-env
    - flax
    - gym
    - numpy
    - optax
    - pillow
    - python >=3.7
    - pytinyrenderer
    - pyyaml >=6.0
    - tensorboardx
    - trimesh
    - typing-extensions
    - grpcio

test:
  imports:
    - brax
  commands:
    - pip check
    # The testdata cylinder.stl is not shipped with the source archive,
    # so we download it manually
    # See:
    # * https://github.com/google/brax/blob/v0.0.16/brax/tests/physics_test.py
    # * https://github.com/abseil/abseil-py/blob/v1.3.0/absl/testing/absltest.py#L156
    - mkdir -p brax/tests/testdata
    - wget https://github.com/google/brax/raw/v{{ version }}/brax/tests/testdata/cylinder.stl -O brax/tests/testdata/cylinder.stl
    - pytest --pyargs brax -v
  requires:
    - pip
    - pytest
    - transforms3d
    - wget

about:
  home: http://github.com/google/brax
  summary: A differentiable physics engine written in JAX.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - erikfrey
