{% set name = "brax" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/brax/archive/refs/tags/v{{ version }}.zip
  sha256: 441341bac198c22333fb6625885e8b2cb6bdff6aa434d8bf097e70e22a7eff66
  patches:
    - fix_assets_urdf.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jaxlib >=0.3.7
    - jax
    - absl-py
    - dataclasses
    - dm-env
    - flask
    - flask-cors
    - flax
    - gym
    - numpy
    - optax
    - pillow
    - python >=3.7
    - pytinyrenderer
    - pyyaml >=6.0
    - tensorboardx
    - trimesh ==3.9.35
    - typing-extensions
    - grpcio
    - jaxopt
    - jinja2
    - mujoco-python
    - etils
    - importlib_resources

test:
  imports:
    - brax
  commands:
    - pip check
    # The testdata cylinder.stl is not shipped with the source archive,
    # so we download it manually
    # See:
    # * https://github.com/google/brax/blob/v0.0.16/brax/tests/physics_test.py
    # * https://github.com/abseil/abseil-py/blob/v1.3.0/absl/testing/absltest.py#L156
    - mkdir -p brax/v1/tests/testdata
    - wget https://github.com/google/brax/raw/v{{ version }}/brax/v1/tests/testdata/cylinder.stl -O brax/v1/tests/testdata/cylinder.stl
    - pytest --pyargs brax -v -k "not (test_joint_ref_check)"
  requires:
    - pip
    - pytest
    - transforms3d
    - wget
    - git

about:
  home: http://github.com/google/brax
  summary: A differentiable physics engine written in JAX.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - erikfrey
